### ISSUE TITLE
Problem with typescript template

### ISSUE THREAD

**Issue by gSarciotto** [nano-react-app/nano-react-app#19]
## Description
I did the quick-start via `npx` and then ran `npm run start` and everythin seemed fine. I then proceed to add linting and formatting without trouble. The problem appeared when I modified `App.tsx` to the following:
```
import * as React from "react";

function App(): JSX.Element {
    return (
        <>
            <h1>Welcome to React Parcel Micro App!</h1>
            <p>Hard to get more minimal than this React app.</p>
        </>
    );
}

export default App;
```
When I run `npm run start`, I receive the following error:
```
@parcel/transformer-babel: Unexpected token, expected "{" (3:14)
SyntaxError: Unexpected token, expected "{" (3:14)
    at Object._raise (/home/code/Desktop/prog/projetos/bug-tracker/frontend/node_modules/@babel/parser/lib/index.js:757:17)
    at Object.raiseWithData (/home/code/Desktop/prog/projetos/bug-tracker/frontend/node_modules/@babel/parser/lib/index.js:750:17)
    at Object.raise (/home/code/Desktop/prog/projetos/bug-tracker/frontend/node_modules/@babel/parser/lib/index.js:744:17)
    at Object.unexpected (/home/code/Desktop/prog/projetos/bug-tracker/frontend/node_modules/@babel/parser/lib/index.js:8834:16)
    at Object.expect (/home/code/Desktop/prog/projetos/bug-tracker/frontend/node_modules/@babel/parser/lib/index.js:8820:28)
    at Object.parseBlock (/home/code/Desktop/prog/projetos/bug-tracker/frontend/node_modules/@babel/parser/lib/index.js:11749:10)
    at Object.parseFunctionBody (/home/code/Desktop/prog/projetos/bug-tracker/frontend/node_modules/@babel/parser/lib/index.js:10758:24)
    at Object.parseFunctionBodyAndFinish (/home/code/Desktop/prog/projetos/bug-tracker/frontend/node_modules/@babel/parser/lib/index.js:10741:10)
    at /home/code/Desktop/prog/projetos/bug-tracker/frontend/node_modules/@babel/parser/lib/index.js:11925:12
    at Object.withTopicForbiddingContext (/home/code/Desktop/prog/projetos/bug-tracker/frontend/node_modules/@babel/parser/lib/index.js:11085:14)
/home/code/Desktop/prog/projetos/bug-tracker/frontend/src/App.tsx:3:14
  2 | 
> 3 | function App(): JSX.Element {
>   |              ^
  4 |     return (
  5 |         <>
```

## Fix?

I dont know much about bundling and Babel, so my guess was that Babel wasn`t configured with Typescript. I searched in the Babel site and found how to configure it [https://babeljs.io/docs/en/babel-preset-typescript]()

I just modified the `preset` in `package.json` to:
```
"babel": {
    "presets": [
      "@babel/preset-typescript",
      "babel-preset-nano-react-app"
    ]
  }
```
and everything worked fine. So I dunno if something changed in Babel and broke the template. Someone else ran into the same issue?

**Comment by Cethy** [comment]
@gSarciotto Just ran into it. And I know even less about Babel, so you saved me a ton of research.

FWIW, removing the `babel` entry from the `package.json` works too. Does Parcel try to guess the right presets ?

**Comment by adrianmcli** [comment]
Ah, sorry that I missed this. Let me test it out right now.

**Comment by adrianmcli** [comment]
@gSarciotto @Cethy thanks for reporting this and commenting. It's been fixed in the template now so it should work!

Please test and let me know if it doesn't.

**Comment by Cethy** [comment]
LGTM :)
